### ISSUE TITLE
unauthorized apple pay network

### ISSUE THREAD

**Issue by maulikm235** [paytabscom/paytabs-ios-library-sample#86]
![image](https://github.com/paytabscom/paytabs-ios-library-sample/assets/69245102/e3be19f9-487f-4a99-9a68-bac5543d424c)
My application was rejected because of this issue.

**Comment by maulikm235** [comment]
The solution is to set up a payment network for Apple Pay which your account is supporting.

**Comment by maulikm235** [comment]
> @maulikm235 What do you mean when you said to set up a payment network? I have added all the certificates in the capabilities and even added the apple pay processing certificate in the payTabs, but I am still getting the error

they said it is solution but it is not.

**Comment by MuhamedAdly** [comment]
Ensure you configured ApplePay correctly using this link:
https://github.com/paytabscom/paytabs-ios-library-sample/blob/master/ApplePayConfiguration.md

**Comment by v-aroundu** [comment]
For me, the issue is solved. For the apple pay to work, you should have an ApplePay account. And ApplePay should be supported in your country.

**Comment by ElSawyMohamed** [comment]
Same for me, and I tried everything but the issue still happened, what's the solution for it ?

**Comment by MuhamedAdly** [comment]
Please make sure ApplePay is available on your device, also you are using live profile credentials, and your device's country is supporting ApplePay, moreover check the card(s) added to the wallet is one of the supported networks if you pass specific countries in the supported networks parameter in the payment SDK configuration.

**Comment by maulikm235** [comment]
> Please make sure ApplePay is available on your device, also you are using live profile credentials, and your device's country is supporting ApplePay, moreover check the card(s) added to the wallet is one of the supported networks if you pass specific countries in the supported networks parameter in the payment SDK configuration.

everything is perfect from the app side, the issue is with this SDK, and they are unwilling to solve it.

**Comment by v-aroundu** [comment]
@maulikm235 which country are you trying to access the ApplePay?

**Comment by maulikm235** [comment]
> @maulikm235 which country are you trying to access the ApplePay?

Saudi Arabia.
